// Code generated by MockGen. DO NOT EDIT.
// Source: myapp/internal/rocket (interfaces: Store)

// Package rocket is a generated GoMock package.
package rocket

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddRocket mocks base method.
func (m *MockStore) AddRocket(arg0 Rocket) (Rocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRocket", arg0)
	ret0, _ := ret[0].(Rocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRocket indicates an expected call of AddRocket.
func (mr *MockStoreMockRecorder) AddRocket(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRocket", reflect.TypeOf((*MockStore)(nil).AddRocket), arg0)
}

// DelRocket mocks base method.
func (m *MockStore) DelRocket(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelRocket", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelRocket indicates an expected call of DelRocket.
func (mr *MockStoreMockRecorder) DelRocket(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelRocket", reflect.TypeOf((*MockStore)(nil).DelRocket), arg0)
}

// GetRocket mocks base method.
func (m *MockStore) GetRocket(arg0 string) (Rocket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRocket", arg0)
	ret0, _ := ret[0].(Rocket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRocket indicates an expected call of GetRocket.
func (mr *MockStoreMockRecorder) GetRocket(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRocket", reflect.TypeOf((*MockStore)(nil).GetRocket), arg0)
}
